### ISSUE TITLE
Compose Sprint

### ISSUE THREAD

**Issue by joshrio** [sceene/sprint-planning#2]
### Post Screen - [Added to iOS sprint #80]

- Borders need to have a RGB: 204, 204, 204 
 - Bottom border on the content/description box
 - Top and bottom borders of Share to: and Share to Sceenes sections

### Music - [Added to iOS sprint #80]

- [ ] Add the Popular tracks query to the initial music screen so there’s no empty state 
- [ ] Disable swipe back so that the user can trim start time easier 
- [ ] Shorten the histogram when the user trims the track
- [ ] Make the histograms height 25% shorter so it doesn’t overlay the box
- [ ] Gray (RGB 127, 127, 127) out the played section of the played track
- [ ] Delete the three white dots in the header by the back button
- [ ] Make the track progress vertical line RGB 127, 127, 127
- [ ] Stop the track from playing once the user has clicked next and goes to the post screen

### Photo - [Added to iOS sprint #80]

- [ ] Add the filters 
 - http://bit.ly/1hkahEo
 - Lets delete all their filters and start from scratch
 - Keep a reference to them so if we don’t do a better job we can still revert to standard
- [ ] Lets delete Stickers and text
- [ ] Can we look at making the options selections like our quote composer
 - I’ve created all the links just let me know if we can do this.
- [ ] Can we lessen the values of contrast. They’re way to aggressive 
 - If the values are +1 / -1 then they can but changed to +.5 / -.5
- [ ] Can we try see if adding light leaks will work
 - http://bit.ly/1K2WoFR
- [ ] Make the editing navigation label buttons say **Save** *not* **Done** in the editing flow

### Quote

- [ ] Default font should be Helvetica Neue Light   - [Added to iOS sprint #80]
- [ ] If you open Quote, click shadow then back - the shadow is applied to the text.   - [Added to iOS sprint #80]
- [ ] Add a top and bottom alignment [Josh agreed not to implement this after seeing it with Lucas]
- [ ] Make the slider 25% shorter   - [Added to iOS sprint #80]
- [ ] Rotation still has a bug that after applying rotation and resign it fly’s off the screen [Josh agreed not to implement this after seeing it with Lucas]
- [ ] When closing quote the keyboard still shows for a second  - [Added to iOS sprint #80]
- [ ] The photo when being applied to the background is super blurry.  - [Added to iOS sprint #80]
- [ ] Make the editing navigation label buttons say **Save** *not* **Done** in the editing flow  - [Added to iOS sprint #80]
- [ ] Remove Zapfino font it’s super ugly!  - [Added to iOS sprint #80]
- [ ] The background icons have a bug with showing another square within the icon.  - [Added to iOS sprint #80]
 - http://imgur.com/O65mjYL
- [ ] Make the stroke on the *black* Background and Color 3px  - [Added to iOS sprint #80]

### Status  - [Added to iOS sprint #80]

- [ ] Change the UI for status 
http://imgur.com/WDoAoww
